# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vllm.entrypoints.pull_worker.proto import queue_pb2 as vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vllm/entrypoints/pull_worker/proto/queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PullWorkerServiceStub:
    """PullWorkerService defines the gRPC interface for disaggregated pull-based workers
    interacting with a central queue orchestrator.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/RegisterWorker',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/ReportStatus',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.WorkerStatus.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.FromString,
                _registered_method=True)
        self.StreamTasks = channel.stream_stream(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/StreamTasks',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.FromString,
                _registered_method=True)
        self.PullTask = channel.unary_unary(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/PullTask',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.FromString,
                _registered_method=True)
        self.StreamOutput = channel.stream_unary(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/StreamOutput',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RequestOutputChunk.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.FromString,
                _registered_method=True)
        self.AbortTask = channel.unary_unary(
                '/vllm.entrypoints.pull_worker.proto.PullWorkerService/AbortTask',
                request_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortRequest.SerializeToString,
                response_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortResponse.FromString,
                _registered_method=True)


class PullWorkerServiceServicer:
    """PullWorkerService defines the gRPC interface for disaggregated pull-based workers
    interacting with a central queue orchestrator.
    """

    def RegisterWorker(self, request, context):
        """Handshake and registration of worker capabilities upon startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """Periodic heartbeat reporting standard and optional extended metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTasks(self, request_iterator, context):
        """Bidirectional credit-based task pull stream. Worker pushes TaskGrantRequest
        (slots_available), and Queue Server streams down GenerateRequest messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullTask(self, request, context):
        """Unary alternative for long-polling task pull.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOutput(self, request_iterator, context):
        """Stream generation outputs (tokens, logprobs, finish reasons) back to queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTask(self, request, context):
        """Abort an in-flight generation task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PullWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.WorkerStatus.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.SerializeToString,
            ),
            'StreamTasks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTasks,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.SerializeToString,
            ),
            'PullTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PullTask,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.SerializeToString,
            ),
            'StreamOutput': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamOutput,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RequestOutputChunk.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.SerializeToString,
            ),
            'AbortTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTask,
                    request_deserializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortRequest.FromString,
                    response_serializer=vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vllm.entrypoints.pull_worker.proto.PullWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vllm.entrypoints.pull_worker.proto.PullWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PullWorkerService:
    """PullWorkerService defines the gRPC interface for disaggregated pull-based workers
    interacting with a central queue orchestrator.
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/RegisterWorker',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerRequest.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/ReportStatus',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.WorkerStatus.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTasks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/StreamTasks',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/PullTask',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.TaskGrantRequest.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.GenerateRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOutput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/StreamOutput',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.RequestOutputChunk.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.ReportStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.entrypoints.pull_worker.proto.PullWorkerService/AbortTask',
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortRequest.SerializeToString,
            vllm_dot_entrypoints_dot_pull__worker_dot_proto_dot_queue__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
